### ISSUE TITLE
query trimming

### ISSUE THREAD

**Issue by icodeforlove** [seegno/sql-tag#6]
The recent commit by @ruimarinho has broken many scenarios.

At the moment this project is mangling data. We should not be doing loose trimming for example the current trimming logic will do the following

```
`SELECT *
FROM`
```

to

```
SELECT *FROM
```

Also

```
UPDATE user SET name = "foo          bar"
```

to

```
UPDATE user SET name = "foo bar"
```

If we are going to do trimming PLEASE add more tests.

**Comment by ruimarinho** [comment]
@icodeforlove thanks for filing this issue. I think your concerns are valid but let me dive deeper into them:
1. Your first example, when used without trimming, is actually outputting `SELECT *\nFROM` to the server. This may or may not be a concern depending on your database, but control characters inside an SQL string can be problematic, depending on the client. In addition to that, please note that `SELECT *FROM` can also be syntactically valid (postgres allows it, for instance).
2. You're not taking advantage of parameterised queries as you're explicitly setting `name` to a literal string in your second example (`foo          bar`). If you [look at the README](https://github.com/seegno/sql-tag#examples), literals should be written as `${'foo'}` so that they are passed as isolated values and, therefore, not subject to any trimming process. Remember that values passed on the SQL string itself are sent as part of the SQL and not subject to the database's own escaping strategies. This poses a high security risk, which parametrised queries help solve in an elegant manner.

Tests [implicitly test trimming](https://github.com/seegno/sql-tag/blob/master/test/index_test.js#L11-L19), so if you take my comments in consideration, I would say that it is enough, as trimming respects only to the SQL syntax, not the values themselves (that would be just crazy).

Perhaps the README could be improved to make this more explicit? What are your suggestions?

**Comment by icodeforlove** [comment]
Well lets change the first example to

```
SELECT 1
WHERE 1 = 1
```

You would get `SELECT 1WHERE` which would probably not be valid. Either way if we want to have aggressive trimming i think this should be some sort of toggle as it currently breaks queries. The engine specific cleanup should happen at the ORM level before it gets sent off to the server.

For example 2 this is true but there are some scenarios where we don't need templated params like

```
SELECT name
FROM user
WHERE 
banned = 0 AND
userid = ${userid}
LIMIT 1
```

We would have to write the above like this

```
SELECT ${'name'}
FROM ${'user'}
WHERE 
${'banned'} = ${0} AND
${'userid'} = ${userid}
LIMIT 1
```

To protect against the current trimming. Either way my point is that we should be able to have multiline code and not have to worry about what our whitespace removal + concatenation layer is doing.

**Comment by ruimarinho** [comment]
I've given this some more thought and I can agree with the fact that some of the library uses, as you've shown, prove that it has a fragile white spacing removal layer if not handled carefully. Since I don't want that to be an impediment to using this library, I have decided to go ahead and remove it. 

I am not sure that an ORM library or a pure SQL driver will handle `SELECT name\nFROM user\nWHERE\nbanned = 0 AND\nuserid = ?\nLIMIT 1` correctly, but in that case the user has the option to adjust the multiline positioning as he sees fit. `sql-tag` can remain agnostic to that.

I will publish this a patch release so that everyone can get this as part of a bug fix cycle. I believe this is the correct semver tag in the interesting of protecting users of misuse.

Thanks for bringing this up.

**Comment by ruimarinho** [comment]
Closed by https://github.com/seegno/sql-tag/pull/7.
